### ISSUE TITLE
Color Wheel Rewrite

### ISSUE THREAD

**Issue by MJoosep** [empire-ai/Unity-Menusystem#2]
**Description**
It should be easier to modify the Color Wheel than it currently is. Color Wheel logic should be rewritten to allow easier modification. Color Wheel menu should pop out from the right side menu rather than being embedded in the Color Wheel Window. Movement Joystick should disappear and instead fine tuning should be done with two fingers/right click.

**Todo:**
- [x] Simplify Color Wheel logic
- [x] Add Color Wheel menu to Right Side Menus
- [x] Toggle to switch between snapping and free movement on Color Wheel
- [ ] #5
- [x] Right Click Joystick on the Color Wheel for fine tuning.

**Review:**
- [ ] Create 1st implementation to send ITHX values as ArtNet values to Apollo 1
